VIEWPORT_WIDTH = 16.0
VIEWPORT_HEIGHT = 10.0
PIXELS_PER_METER = 60

SCREEN_WIDTH = int(VIEWPORT_WIDTH * PIXELS_PER_METER)
SCREEN_HEIGHT = int(VIEWPORT_HEIGHT * PIXELS_PER_METER)

GRAVITY = -30.0
PHYSICS_DT = 1.0 / 60.0
MAX_PHYSICS_STEPS = 5

FUEL_MAX = 100.0
FUEL_CONSUMPTION_RATE = 2.5
FUEL_IDLE_CONSUMPTION = 0.5
FUEL_CAN_RESTORE = 80.0

FUEL_CAP_UPGRADE_BONUS = 40.0

COIN_RADIUS = 0.2
FUEL_CAN_RADIUS = 0.25

AIR_CONTROL_TORQUE = 25.0
STEEP_SLOPE_ANGLE = 0.6
SLOPE_FRICTION_REDUCTION = 0.3
LANDING_DAMPING_BOOST = 8.0
LANDING_DAMPING_DECAY = 3.0

FRICTION_ZONE_LENGTH = 12.0
ICE_FRICTION = 0.15
MUD_FRICTION = 0.35
MUD_DRAG = 0.6

TERRAIN_CHUNK_WIDTH = 8.0
TERRAIN_POINTS_PER_CHUNK = 80
TERRAIN_CHUNKS_AHEAD = 4
TERRAIN_CHUNKS_BEHIND = 2

FUEL_PICKUP_INTERVAL = 80.0
GHOST_RECORD_INTERVAL = 6
